version: 2.1

executors:
  python-executor:
    machine:
      enabled: true
    working_directory: ~/trade-data-catalogue

jobs:
  install_dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Python and pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt 
  
  run_django_tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Python and pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-dev
            python3 -m venv venv 
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Django tests
          command: |
            . venv/bin/activate
            cd trade_data_catalogue
            python manage.py test

workflows:
  version: 2
  test:
    jobs:
      - run_django_tests
