version: 2.1

executors:
  python-executor:
    machine:
      enabled: true
    working_directory: ~/trade-data-catalogue
  cypress-executor:
    machine:
      enabled: true
    working_directory: ~/trade-data-catalogue

jobs:
  run_django_tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Python and pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-dev
            python3 -m venv venv 
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run Django tests
          command: |
            . venv/bin/activate
            cd trade_data_catalogue
            python manage.py test

  run_cypress_tests:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Install Python and pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-dev
            python3 -m venv venv 
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Start Django server
          command: |
            cd trade_data_catalogue
            python manage.py runserver
            cd ..
          background: true

      - run:
          name: Wait for Django server
          command: |
            until curl -s http://localhost:8000; do sleep 1; done

      - run:
          name: Install npm and Cypress
          command: |
            npm install
            npm install cypress

      - run:
          name: Run Cypress tests
          command: |
            npx cypress run

workflows:
  version: 2
  test:
    jobs:
      - run_django_tests
      - run_cypress_tests
