version: 2.1

executors:
  default_executor:
    machine: true

jobs:
  environment_setup:
    executor: default_executor
    steps:
      - checkout
      - run:
          name: Install Python and pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-dev
            python3 -m venv venv 
            . venv/bin/activate
            pip install -r requirements.txt
      
      - run:
          name: Install npm and Cypress
          command: |
            npm install
            npm install cypress

      - persist_to_workspace:
          root: .
          paths:
            - venv
            - .

  run_django_tests:
    executor: default_executor
    steps:
      - attach_workspace:
          at: /home/circleci/trade-data-catalogue

      - run:
          name: Run Django tests
          command: |
            cd /home/circleci/trade-data-catalogue
            . venv/bin/activate
            pip list
            cd trade_data_catalogue
            python manage.py test

  run_cypress_tests:
    executor: default_executor
    steps:
      - attach_workspace:
          at: /home/circleci/trade-data-catalogue

      - run:
          name: Start Django server
          command: |
            cd /home/circleci/trade-data-catalogue
            . venv/bin/activate
            cd trade_data_catalogue
            python manage.py runserver
            cd ..
          background: true

      - run:
          name: Wait for Django server
          command: |
            until curl -s http://localhost:8000; do sleep 1; done

      - run:
          name: Run Cypress tests
          command: |
            npx cypress run

workflows:
  version: 2
  test:
    jobs:
      - environment_setup
      - run_django_tests:
          requires:
            - environment_setup
      - run_cypress_tests:
          requires:
            - environment_setup
